# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 650)
        MainWindow.setMinimumSize(QtCore.QSize(350, 650))
        MainWindow.setMaximumSize(QtCore.QSize(350, 650))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_volume = QtWidgets.QLabel(self.centralwidget)
        self.label_volume.setGeometry(QtCore.QRect(20, 390, 101, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_volume.setFont(font)
        self.label_volume.setObjectName("label_volume")
        self.dial_channel = QtWidgets.QDial(self.centralwidget)
        self.dial_channel.setGeometry(QtCore.QRect(220, 480, 111, 111))
        self.dial_channel.setMinimum(1)
        self.dial_channel.setMaximum(3)
        self.dial_channel.setWrapping(False)
        self.dial_channel.setNotchesVisible(True)
        self.dial_channel.setObjectName("dial_channel")
        self.label_channel = QtWidgets.QLabel(self.centralwidget)
        self.label_channel.setGeometry(QtCore.QRect(240, 400, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_channel.setFont(font)
        self.label_channel.setObjectName("label_channel")
        self.label_dial1 = QtWidgets.QLabel(self.centralwidget)
        self.label_dial1.setGeometry(QtCore.QRect(230, 570, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_dial1.setFont(font)
        self.label_dial1.setObjectName("label_dial1")
        self.label_dial2 = QtWidgets.QLabel(self.centralwidget)
        self.label_dial2.setGeometry(QtCore.QRect(270, 450, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_dial2.setFont(font)
        self.label_dial2.setObjectName("label_dial2")
        self.label_dial3 = QtWidgets.QLabel(self.centralwidget)
        self.label_dial3.setGeometry(QtCore.QRect(310, 580, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_dial3.setFont(font)
        self.label_dial3.setObjectName("label_dial3")
        self.slider_volume = QtWidgets.QSlider(self.centralwidget)
        self.slider_volume.setGeometry(QtCore.QRect(40, 440, 22, 160))
        self.slider_volume.setMaximum(100)
        self.slider_volume.setPageStep(10)
        self.slider_volume.setOrientation(QtCore.Qt.Vertical)
        self.slider_volume.setObjectName("slider_volume")
        self.label_volume_0 = QtWidgets.QLabel(self.centralwidget)
        self.label_volume_0.setGeometry(QtCore.QRect(70, 582, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_volume_0.setFont(font)
        self.label_volume_0.setObjectName("label_volume_0")
        self.label_volume_100 = QtWidgets.QLabel(self.centralwidget)
        self.label_volume_100.setGeometry(QtCore.QRect(70, 440, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_volume_100.setFont(font)
        self.label_volume_100.setObjectName("label_volume_100")
        self.button_power = QtWidgets.QPushButton(self.centralwidget)
        self.button_power.setGeometry(QtCore.QRect(150, 300, 51, 51))
        self.button_power.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("power.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_power.setIcon(icon)
        self.button_power.setIconSize(QtCore.QSize(50, 50))
        self.button_power.setDefault(False)
        self.button_power.setObjectName("button_power")
        self.button_mute = QtWidgets.QPushButton(self.centralwidget)
        self.button_mute.setGeometry(QtCore.QRect(10, 500, 31, 31))
        self.button_mute.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("mute.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_mute.setIcon(icon1)
        self.button_mute.setIconSize(QtCore.QSize(25, 25))
        self.button_mute.setObjectName("button_mute")
        self.display = QtWidgets.QLabel(self.centralwidget)
        self.display.setGeometry(QtCore.QRect(30, 20, 281, 181))
        self.display.setText("")
        self.display.setPixmap(QtGui.QPixmap("black.jpg"))
        self.display.setScaledContents(True)
        self.display.setObjectName("display")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_volume.setText(_translate("MainWindow", "VOLUME"))
        self.label_channel.setText(_translate("MainWindow", "CHANNEL"))
        self.label_dial1.setText(_translate("MainWindow", "1"))
        self.label_dial2.setText(_translate("MainWindow", "2"))
        self.label_dial3.setText(_translate("MainWindow", "3"))
        self.label_volume_0.setText(_translate("MainWindow", "0"))
        self.label_volume_100.setText(_translate("MainWindow", "100"))

    def show_news(self):
        self.display.setPixmap(QtGui.QPixmap("news.jpg"))
    def show_cartoon(self):
        self.display.setPixmap(QtGui.QPixmap("spongebob.jpg"))
    def show_animal(self):
        self.display.setPixmap(QtGui.QPixmap("discovery_channel.jpg"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
